Extract range queries and record iterator
JanusGraph/janusgraph-foundationdb pull request #46
Opened 2020-07-30 08:09 UTC by rngcntr

Main changes:

1. Introduce the class `FoundationDBRangeQuery`
- This class replaces the old representation of range queries as `Object` arrays

2. Extract the `FoundationDBRecordIterator` into it's own file
- Unpacking the key-value pairs was also moved to the iterator class to keep the `FoundationDBKeyValueStore` class clean.

2020-07-30 13:00 UTC, mbrukman commented
@rngcntr — please add a DCO sign-off to your commit and `git push -f`.

Please see these instructions for how to do it for this PR, and make this automatic in your repo clone for future commits: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin — I do this for all JanusGraph repos that I clone to avoid forgetting to do this.

2020-07-30 13:06 UTC, rngcntr commented
@mbrukman Sorry I somehow forgot to sign the commit. Thanks for mentioning

2020-08-18 12:22 UTC, rngcntr commented
@mbrukman @blindenvy Would anyone of you like to review this? I did a lot of refactoring here and would prefer to take some of your opinions into account before continuing further development based on these changes.

2020-08-18 14:44 UTC, farodin91 commented
@rngcntr Could you rebase this on top of the master

2020-09-22 21:03 UTC, farodin91 requested changes
Basically one question and three small changes.

2020-09-22 21:03 UTC, farodin91 commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    static final StaticBuffer.Factory<byte[]> ENTRY_FACTORY = (array, offset, limit) -> {
nit: All properties should have a visibility modifier.

2020-09-22 21:03 UTC, farodin91 commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +        final List<KeyValue> result = tx.getRange(new FoundationDBRangeQuery(db, query));
Why you removed the try and catch?

2020-09-22 21:03 UTC, farodin91 commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRangeQuery.java
> +package org.janusgraph.diskstorage.foundationdb;
All new added class should have the licenses header.

2020-09-22 21:03 UTC, farodin91 commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java
> +package org.janusgraph.diskstorage.foundationdb;
All new added class should have the licenses header.

2020-09-23 05:11 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +        final List<KeyValue> result = tx.getRange(new FoundationDBRangeQuery(db, query));
Because it does nothing else but to repeat the exception.
The `getRange` call throws a `PermanentBackendException` and the `catch` block just wraps it within another `PermanentBackendException`. To me, there is no sense in doing so.

2020-09-23 05:19 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    static final StaticBuffer.Factory<byte[]> ENTRY_FACTORY = (array, offset, limit) -> {
The best practice is to always use the most restrictive access level that fits the needs. In this case, private is too restrictive, because `FoundationDBRangeQuery` needs access. `public` is too unrestrictive, because this field does not need to be visible to classes outside of the FDB Storage adapter. Therefore "package-private" is what I went for. In Java, not specifying a modifier means package private and there is no way to explicitly express this level of restriction.

2020-10-04 11:54 UTC, farodin91 approved these changes
LGTM! Thank you @rngcntr

2020-10-05 06:35 UTC, merged