Add range and partition support on FoundationDB adapter for batch processing
JanusGraph/janusgraph-foundationdb pull request #48
Opened 2020-08-27 20:59 UTC by ruweih

2020-08-31 11:30 UTC, rngcntr requested changes
Thanks for your contribution @ruweih!
Using FoundationDB's [async reads](https://apple.github.io/foundationdb/javadoc/com/apple/foundationdb/ReadTransaction.html) is a very nice idea. But actually, I don't really know where `getSliceAsync` will be used in JanusGraph. Is it used at all?

2020-08-31 11:30 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public Iterator<KeyValueEntry> getSliceAsync(byte[] keyStart, byte[] keyEnd, int limit, KeySelector selector, StoreTransaction txh) throws BackendException {
For convenience, `getSliceAsync` should have the same signature as `getSlice`.

2020-08-31 11:30 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        return tx.getRange(startKey, endKey, limit);
This method will block until the full list of results is ready, which is not what one would expect from the method name.
I would prefer to move the logic of the `getRange` method here and design it so that it runs in a properly async manner. Then all that's left to do is call `getRangeAsync` within `getRange` and additionally wait for it's completion before returning the results.

2020-08-31 11:30 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public List<StaticBuffer> getBoundaryKeys() {
Where is this method called? Is it somewhere inside JanusGraph where the `OrderedKeyValueStore` is used?

2020-10-02 16:05 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        return tx.getRange(startKey, endKey, limit);
From the method signature , it seems return an async result, that's why I choose the name for this method:
https://apple.github.io/foundationdb/javadoc/com/apple/foundationdb/ReadTransaction.html#getRange-byte:A-byte:A-int-

2020-10-02 16:13 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public Iterator<KeyValueEntry> getSliceAsync(byte[] keyStart, byte[] keyEnd, int limit, KeySelector selector, StoreTransaction txh) throws BackendException {
Maybe, but we can not use the inner class "FoundationDBRecordIterator" since it requires data been retrieved first, which defeat the purpose of this method to not retrieving data in memory first.

2020-10-02 16:14 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public List<StaticBuffer> getBoundaryKeys() {
As I mentioned in PR, those method are not called within JG, it's used for bulk access in Spark jobs.

2020-10-05 06:06 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        return tx.getRange(startKey, endKey, limit);
Huh, I'm pretty confident at the time I wrote this comment, there were both `getRange` and `getRangeAsync` available in FDB. But now my comment is obsolete of course :smile:

2020-10-05 06:15 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public Iterator<KeyValueEntry> getSliceAsync(byte[] keyStart, byte[] keyEnd, int limit, KeySelector selector, StoreTransaction txh) throws BackendException {
FoundationDB offers an [`AsyncIterable`](https://apple.github.io/foundationdb/javadoc/com/apple/foundationdb/async/AsyncIterable.html) which extends `Iterable`. You could maybe modify the `FoundationDBRecordIterator` to not take a `List` in it's constructor but any `Iterable`. This way it would be possible to use the `FoundationDBRecordIterator` for async results.

2020-12-04 00:00 UTC, pluradj commented
@ruweih Regarding the CLA check, please fix your commits so that you sign them with your IBM email address instead of your Gmail address. Thanks.

2020-12-04 00:28 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +    public Iterator<KeyValueEntry> getSliceAsync(byte[] keyStart, byte[] keyEnd, int limit, KeySelector selector, StoreTransaction txh) throws BackendException {
getSliceAsync is introduced from other PR recently, so no need this method any more.

2020-12-04 00:32 UTC, porunov commented
@ruweih Thank you for the contribution! You have 4 commits in this PR and two of them are not signed properly. If you squash and sign you commit, EasyCLA will pass. Let me know if you have troubles squashing those commits and I will help

2020-12-04 00:34 UTC, ruweih commented
> @ruweih Regarding the CLA check, please fix your commits so that you sign them with your IBM email address instead of your Gmail address. Thanks.

How could we change the existing commits?

2020-12-04 00:39 UTC, ruweih commented
> @ruweih Thank you for the contribution! You have 4 commits in this PR and two of them are not signed properly. If you squash and sign you commit, EasyCLA will pass. Let me know if you have troubles squashing those commits and I will help

Thanks. I used git desktop to merge from master, which for some reason does not signed it properly, how do I change the signature of those existing commits?

2020-12-04 00:57 UTC, porunov commented
> Thanks. I used git desktop to merge from master, which for some reason does not signed it properly, how do I change the signature of those existing commits?

@ruweih There are different ways to do it. In you situation, you have some merge commits. You could use `git rebase` to pick one commit and squash other commits in it ( i.e. `git rebase -i 4408551d42c3fafeeee70f103f28fefb409022d3`) but in your situation you will also need to resolve conflicts and then do `git rebase --continue` after the resolutions.

In some cases you know that you PR changes are good and you don't want to worry about past commits and resolve merge commits conflicts. If so, you can merge you branch into the target branch with a squash and then reset you feature branch from target branch, push it and then reset you local target branch from origin (or anything else to remove you squashed merge commit).
So, basically, to simplify current squash process I would basically do something like:
```
git checkout master
git merge --squash rangekeys-ruweih
git commit -m "Add range and partition support on FoundationDB adapter for batch processing" -s
git checkout rangekeys-ruweih
git reset --hard master
git push -f
git checkout master
git reset --hard origin/master
```
That said, you can use any other technique to squash your commits but make sure to sign them properly with `-s` parameter.

2020-12-04 16:58 UTC, ruweih commented
@porunov Thanks for the help. All checks been passed after the fix.

@rngcntr The updated PR removed the need for own async iterator, which should address your previous comment. Please review again and clean the change request.

2020-12-07 08:54 UTC, rngcntr approved these changes
LGTM

2020-12-08 22:25 UTC, ruweih commented
@rngcntr Seems I don't have the write permission to merge it. Could you or someone else please merge the PR in your convenience if there is no more issue need to be addressed?

2020-12-08 22:51 UTC, porunov commented
@ruweih - `two committer approvals` OR `one committer approval + 1 week for lazy consensus` is needed to merge the PR

2020-12-10 07:40 UTC, theZiki commented
Can somebody merge this, I am waiting for this fix for one year :-)

2020-12-10 08:27 UTC, rngcntr commented
@theZiki We need either another committer to approve the PR or wait another four days until we are good to go.
Although you are not currently a committer, you are welcome to review the PR, making the review process easier for other committers. 
(Just in general, probably not as relevant for this relatively small change)

2021-01-26 18:05 UTC, davisdk commented
I've also got my eyes on this one. :] Any chance we can get it merged shortly? Thanks!

2021-01-27 07:36 UTC, rngcntr commented
@davisdk Thanks for reminding me. Since there were no remarks by others, we can merge this PR now.

2021-01-27 07:36 UTC, merged