async iterator final submission
JanusGraph/janusgraph-foundationdb pull request #50
Opened 2020-10-04 08:07 UTC by jlazdw

This PR is to introduce asynchronous Iterator for getSlice And getSlices methods in FoundationDBKeyvalueStore.java ,to greatly leverage FoundationDB’s Asynchronous Iterator for on-demand data stream pulling, better memory efficiency, better parallelism for MultiQuery support. The asynchronous iterator relies on the FDB java library to take care of Completable Futures, rather than introducing additional Completable Futures in this storage plugin. 

To support this new Async Iterator mode, we introduce “iterator” mode in FoundationDBConfigOptions.java. The existing getSlice and getSlices() is in the new (default) mode called “list” mode, as the query result from FDB java library gets converted to List-based result immediately.

We also provide the fix on getSlices in the current implementation.

2020-10-05 06:43 UTC, rngcntr commented
That sound like a very good improvement to me, thanks @jlazdw!
I'm kindly asking @ruweih to help me out reviewing it, because he is also working on an asynchonous implementation of `getSlice`.

2020-10-06 14:27 UTC, blindenvy commented
+1 Thanks for the contribution @jlazdw

2020-10-06 14:32 UTC, blindenvy reviewed
+1 LGTM. Thank you so much for this contribution @jlazdw

2020-10-07 16:42 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
Seems we can extend from existing FoundationDBRecordIterator with a new constructor accepting iterator if record instead of list of records:
https://github.com/JanusGraph/janusgraph-foundationdb/blob/e8cf024519045f501a7ad83b8090c61e9ebd82b3/src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java

In the constructor of this class, we can leverage the Guava's iterator utility to make the code cleaner:

```
            Iterator<KeyValue> entries = Iterators.filter(
                Iterators.transform(result, keyValue -> {
                    StaticBuffer key = getBuffer(db.unpack(keyValue.getKey()).getBytes(0));
                    if (selector.include(key)) {
                        return new KeyValueEntry(key, getBuffer(keyValue.getValue()));
                    } else {
                        return null;
                    }
                }),
                keyValue -> keyValue != null);
        }
       super(entries);

```

We can then reuse the base class implementation on iterator interface

2020-10-08 08:33 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
@ruweih:  I tried to incorporate your suggestion to the code. and I just found that the code that you suggested above can not be compiled, as  Iterator<KeyValue> entries has the type "KeyValue" and the inner transformer returns the type "KeyValueEntry". The type "KeyValue" and "KeyValueEntry" has no inheritance relationship.   

The current class "FoundationDBRecordIterator.java"  has the private member: 

private final Iterator<KeyValue> entries

It is  at the method of "next" that the "KeyValueEntry" gets constructed on the fly.  The Selector logic is applied at "FoudationDBKeyValueStore" getSlice method, before the FoundationDBRecordIterator object is constructed. https://github.com/JanusGraph/janusgraph-foundationdb/blob/master/src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java#L134. 

Therefore, if we want to keep the current FoundationDBRecordIterator's interface of using "KeyValue" and the current implementation in FoundationDBKeyValueStore's getSlice method, it is better to keep the "KeyValueEntry" construction only at the "next" method for FoundationDBRecordIteratorForAsync, just like FoundationDBRecordIterator's current implementation, instead of having the KeyValueEntry constructed at the constructor time. 

Furthermore, unlike the synchronous iterator (that is, the current FoundationDBRecordIterator.java), our asynchronous iterator will need to re-start the  FDB transaction if the transaction is too old, under "read_commit_with_write" mode, this is shown in the fetchNext() method of FoundationDBRecordIteratorAsync.java.  As a result, for a long query, we need to construct many times, the re-newed version of "entries"  with type of AsyncIterator<KeyValue>. Therefore, the  Guava's Iterator based code will have to be invoked not just in the constructor but also in the fetchNext() method, which makes the code sort of duplicated. 

If you have better way to refactor the code for the Record Iterator and the FoundationDBKeyvalueStore, please provide more details and I will incorporate your suggestion to the code.

2020-10-09 07:57 UTC, rngcntr requested changes
Thanks for adding so many log outputs everywhere, that will certainly help us out hunting bugs in the future!

I've added a few comments, most of them requesting minor changes. The reason why I don't approve this PR yet is that almost none of the changes are covered in the existing tests. I think to ensure the integrity of the async methods and the iterator, we should also run the existing tests in `iterator` mode.

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +    private boolean handleFDBException(Exception e) {
I don't quite understand the purpose of this method. When is it intended to return true, once the corresponding code has been added?
At the moment, it looks like this method should be `void` and called `logFDBException`.

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        int counter = 0;
The counter is never used.

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public byte[] get(final byte[] key) throws PermanentBackendException {
A lot of this method's complexity was removed in #45 without affecting it's semantics. It looks like you reverted most of that. Is there a real purpose behind this change or did it happen by accident?

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public List<KeyValue> getRange(final FoundationDBRangeQuery query) throws PermanentBackendException {
Same as for `get(...)`

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        KeySelector begin = query.getStartKeySelector().add(skip);
Very nice, appreciate this idea!

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +                List<FoundationDBRangeQuery> immutableRetries = retries.stream().collect(toList());
Nit: The Java Stream API is rather slow compared to just creating a new list and passing `retries` as an argument to the constructor.

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +                                    resultMap.put(query, Collections.emptyList());
Thanks for the explanation about the deadlock, sounds plausible to me!

2020-10-09 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +            if (e instanceof BackendException) {
See my other comment.

2020-10-09 08:19 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
@rngcntr: thanks for the suggestion on having KeySelector to be pushed down to both synchronous iterator and the asynchronous iterator.  Let me try to make the corresponding changes and re-submit the PR.

2020-10-09 08:26 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +public class FoundationDBRecordIteratorForAsync implements RecordIterator<KeyValueEntry> {
@rngcntr: the current code does pass all of the required tests. In the PR submission, the option in FoundationDBContainer.java is set to be at:
            .set(ISOLATION_LEVEL, "read_committed_with_write")
            .set(GET_RANGE_MODE, "iterator")

Do you suggest that to modify the mvn test, so that all of the current tests run for first in the "list" mode, and then for "iterator" mode, in sequence?

2020-10-09 08:34 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +public class FoundationDBRecordIteratorForAsync implements RecordIterator<KeyValueEntry> {
Oh I'm sorry, the `FoundationDBContainer.java` went under my radar. But then it's the same thing just the other way around and none of the tests will use the "old" iterator now, right?
I think if both are going to be published, both should always be used in the tests. If that is better achieved in Maven or by generalizing the tests to use both configurations is up to you :smile:

2020-10-12 02:12 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +public class FoundationDBRecordIteratorForAsync implements RecordIterator<KeyValueEntry> {
@rngcntr: I now introduced an environment variable called "getrangemode" that can be set as "iterator" and "list" as:

-Dgetrangemode=iterator

or -Dgetrangemode=list 

to control the test execution. The environment variable is picked up by FoundationDBContainer.java and then gets pushed to FoundationDB Graph Configuration options. 

Correspondingly, I have changed the .travis.yml to augment the tests to have both "iterator" and "list" modes into the tests, effectively double the number of the tests that need to be run.

2020-10-12 02:14 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBStoreManager.java
> +    public static final int ASYNC = 0, NON_ASYNC = 1;
@rngcntr: I now have  in FoundationDBStoreManagers.java:

public enum RangeQueryIteratorMode { ASYNC, SYNC };

to control which get-range mode is chosen.  

I also updated README.md to explain the get-range-mode that is newly introduced in this PR.

2020-10-12 02:18 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBStoreManager.java
> +            if (ex instanceof BackendException) {
@rngcntr: I know change the exception handling body for all of the places that handle BackendException, to be: 

try {

}
catch (BackendException e) {
     throw e;
} 
catch (Exception e) {
      throw new PermanentBackendException (e)
}

Basically, if the exception is already BackendException, we re-throw it , but if it is not an BackendException, we wrap it as a PermanentBackendException, and throw it to JanusGraphCore that handles the transaction processing.

2020-10-12 02:19 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import java.util.LinkedList;
Yes. Clean up the class import after current code change.

2020-10-12 02:24 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
@rngcntr: with your suggestion above, I refactoring FoundationDBRecordIterator and FoundationDBRecordAsyncIterator, to have FoundationDBRecordAysncIterator to inherit from FoundationDBRecordIterator. The hasNext() and next() logic is in the base class of FoundationDBRecordIterator. The difference is on the fetchNext() logic.  The async iterator requires possible transaction re-start in fetchNext() logic. 

The Selector logic is implemented in the base class, FoundationDBRecordIterator. It exposes the cursor "fetched",  that allows the async iterator to set the "skip" offset when the transaction gets re-started and the getRangeIter() gets invoked again.

2020-10-12 02:28 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +                List<FoundationDBRangeQuery> immutableRetries = retries.stream().collect(toList());
Yes. Simply uses:

 List<FoundationDBRangeQuery> immutableRetries = new ArrayList<> (retries);

2020-10-12 02:30 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> +            if (e instanceof BackendException) {
@rngcntr: with the latest code to refactor FoundationDBRecordIterator and FoundationDBRecordAsyncIterator, the selector logic is now pushed into the iterator itself, and thus make the FoundationDBKeyValueStore.java  getSlice () and getSlices() methods much cleaner.

2020-10-12 02:32 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import com.apple.foundationdb.KeyValue;
Yes. all un-used class imports get cleaned up.

2020-10-12 02:33 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        int counter = 0;
I now have the log statement to log this counter for better debugging.

2020-10-12 04:21 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +    private boolean handleFDBException(Exception e) {
Thanks for the suggestion. I changed it to be logFDBException with void return.

2020-10-12 04:28 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public byte[] get(final byte[] key) throws PermanentBackendException {
First, we added the following logic to handle the exception in the get() method and getRange() method:

               if (i+1 != maxRuns) {
                    this.restart();
                } else {
                    lastException = e;
                    break;
                }

That is,  for the last iteration, we do not restart the transaction any more, as no one will pick up the restarted transaction any more 

Second, we add logFDBException so that in debug mode, we have better understanding on what FDB exception gets thrown and the nature of it:  retryable, maybe-committed, not-committed, etc.

Third, we have the finally thrown PermanentBackendException to carry the exception being thrown as:

  if (failing) {
            throw new PermanentBackendException("FDB transaction throws an exception", lastException);
}

In summary, by enriching the exception handling body, we fixed the transaction re-start logic, better logging and better exception propagation.

2020-10-12 04:28 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public List<KeyValue> getRange(final FoundationDBRangeQuery query) throws PermanentBackendException {
See my response above on method get().

2020-10-12 07:55 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
Sounds like a well designed solution to me! I'll most probably have another look at it later this week.

2020-10-12 07:57 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +public class FoundationDBRecordIteratorForAsync implements RecordIterator<KeyValueEntry> {
Thanks!
I think it's reasonable to double the number of tests in this case.

2020-10-12 08:05 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public byte[] get(final byte[] key) throws PermanentBackendException {
What I referred to was the elimination of `boolean failing` and `byte[] value` because both are not needed and the control flow becomes much easier to read and understand if they are removed.

2020-10-12 17:35 UTC, ruweih commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
@jlazdw The code snippet in my previous post was from my POC of async iterator on original 0.1.0 release code, which seems having difference signature: https://github.com/JanusGraph/janusgraph-foundationdb/blob/v0.1.0/src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java#L148

With the current code base, it could be further simplified to just return KeyValue:
```
            Iterator<KeyValue> entries = Iterators.filter(
                Iterators.transform(result, keyValue -> {
                    StaticBuffer key = getBuffer(db.unpack(keyValue.getKey()).getBytes(0));
                    if (selector.include(key)) {
                        return keyValue;
                    } else {
                        return null;
                    }
                }),
                keyValue -> keyValue != null);
        }
       super(entries);
```

The transaction restart logic could happen inside the inner iterators mapping method as well. I noticed there is new changes been checked in , this might not necessary as long as the common iteration logic been reused.

2020-10-12 17:43 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIteratorForAsync.java
> +}
@ruweih: the difficulty that I run into to try to  use the above Iterators filter/transform that you suggested is that I need to record the cursor "fetched", so that when the transaction gets restarted in the Async iterator (inherited from the FoundationDBRecordIterator), I can skip the entries that have been already fetched. This state information will have to be recorded at the iterator level.   https://github.com/jlazdw/janusgraph-foundationdb/blob/Async_iterator_final_submission/src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java#L60

Could you help come up with the way to incorporate the state  "fetched" tracking using the filter/transform, if that is possible?

2020-10-13 09:47 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public byte[] get(final byte[] key) throws PermanentBackendException {
@rngcntr: thanks for the suggestion. In the latest code change, I removed boolean failing and byte[] values, to keep the original code's flow, for both get() and getRange() two methods. Please review the code. change.

2020-10-13 09:47 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public List<KeyValue> getRange(final FoundationDBRangeQuery query) throws PermanentBackendException {
In the latest code change, I removed boolean failing and byte[] values, to keep the original code's flow, for both get() and getRange() two methods. Please review the code. change.

2020-10-14 07:54 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
>      public byte[] get(final byte[] key) throws PermanentBackendException {
@rngcntr:  I believe that the above issue is the final issue that you have raised so far and I have addressed all of them in the latest code. If you have further comments regarding this PR, please let me know. copy @blindenvy.

2020-10-14 08:40 UTC, rngcntr requested changes
Looks much cleaner now, thank you @jlazdw!
Only two more suggestions that came to my mind. I hope you are not annoyed yet :smile:

2020-10-14 08:40 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java
> +        return result;
The implementation of `next()` does not match the expectation of what an Iterator does:
https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--

Repeated calls of `next()` without an intermediate `hasNext()` should still continue the iteration. In other words, `next()` should not rely on `hasNext()` being called.
In addition, calling `next()` on an exhausted iteration should result in a `NoSuchElementException`, not `null`.

2020-10-14 08:40 UTC, rngcntr commented on src/test/java/org/janusgraph/FoundationDBContainer.java
> +        String getRangeMode = getAndCheckRangeModeFromTestEnvironment();
Nit: You could just keep this method as it was before and only append
```java
    .set(GET_RANGE_MODE, getAndCheckRangeModeFromTestEnvironment());
```
to the list of settings.

2020-10-17 06:24 UTC, jlazdw commented on src/test/java/org/janusgraph/FoundationDBContainer.java
> +        String getRangeMode = getAndCheckRangeModeFromTestEnvironment();
Ack.

2020-10-17 06:39 UTC, jlazdw commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java
> +        return result;
@rngcntr: thanks for the suggestion on the iterator interface. I have made some changes following your suggestion. Over the last two days when I was making a proposal on TransactionContext to the JanusGraph developer community, https://github.com/JanusGraph/janusgraph/issues/2238,  I realize that for Threaded Transactions, the current Async Iterator will need to address multiple threads to re-set the same transaction. So I will make further changes in the next several days to handle the threaded transaction. 

I have two related questions:  (1) why in the current master branch,  the test class of FoundationDBGraphConcurrentTest gets "disabled", https://github.com/JanusGraph/janusgraph-foundationdb/blob/master/src/test/java/org/janusgraph/graphdb/foundationdb/FoundationDBGraphConcurrentTest.java#L29
(2) The related JanusGraphConcurrentTest's test cases only creates a Transaction object in each worker thread launched, it is not Threaded Transaction at all, based on the "threaded transaction" definition described at: https://docs.janusgraph.org/basics/transactions/. 

In fact, there is no test in the current JanusGraph test suites to test out threaded transactions, by searching the method invocation of "createThreadedTx()" in the entire test JanusGraph test suite. 

That brings the question on: whether the current JanusGraph really support "threaded transaction" or not?

2020-10-19 08:25 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRecordIterator.java
> +        return result;
Regarding your first question: The test was already failing when we took over the project and until now, nobody started to investigate why. There's an open issue to resolve the failing test case: #28 

For the second question I get your point but I have no Idea about JanusGraph's transaction handling and I feel unable to give any qualified answer to that. If you see a serious problem here, you should maybe report it to the janusgraph-dev mailing list.

2020-10-19 08:30 UTC, rngcntr approved these changes

2020-11-15 16:33 UTC, farodin91 commented
@jlazdw Do you want to squash all commits? Afterwards we should be able to merge it.

2020-11-16 10:33 UTC, jlazdw commented
@farodin91: I have squashed all the commits up to the merge point. In between my commits, there was a PR merge to master. And thus the other commit 086b8abfb1321be241f3f68a17be85a1cfcf04f1 separated my commits. Please let me know if you like me to squash further or the current squash is OK.  I am working on improving the async iterator further (including enable the FoundationDBGraphConcurrentTest related tests that have been disabled in current master). I will try to make another PR in the next two weeks.

2020-11-16 11:44 UTC, farodin91 commented
@jlazdw In the normal case, we just want to have one commit in top of the current it possible. It would be great.

2020-11-16 11:45 UTC, farodin91 commented
> I am working on improving the async iterator further (including enabling the FoundationDBGraphConcurrentTest related tests that have been disabled in current master). I will try to make another PR in the next two weeks.

Sounds awesome

2020-11-16 18:58 UTC, jerryjch commented
@farodin91 I think we can also use the "Squash and Merge' option to merge this PR. There is no conflict to merge.

2020-11-16 19:18 UTC, jlazdw commented
@farodin91: I talked to Jerry and he suggested above on "Squash and Merge" from your side when you merge the PR to the master. If you perform squash, could you use the following last commit message from my submission branch: https://github.com/jlazdw/janusgraph-foundationdb/commit/ec1ca28c37f019ae8c1c76aac6ba23b60be93392, which is:

"
introduce asynchronous iterator
unify the interface for synchronous iterator and asynchronous iterator
minor clean-up on code for logging and class import and refactor record iterators (sync and async)

minor changes to the code:
*re-defining enum for sync and asyn iterator
*backend exception propagation clean-up

made changes to test environment and README.md:
*introduce environment-controlled option to use iterator or list mode for testing
*add -Dgetrangemode=iterator and -Dgetrangemode=list to Travis CI jobs
*add section in README.md to explain iterator/list mode choice for GetRange related queries

"

2020-11-17 09:40 UTC, farodin91 approved these changes
Thank you!

2020-11-17 09:41 UTC, merged