parameterised log message, final variable migration, removing unused methods
JanusGraph/janusgraph-foundationdb pull request #60
Opened 2021-06-24 16:21 UTC by nischalkumar

Small refactor to improve code quality. This pr includes three things

- migrating logs to parameterized slf4j error messages
- removing unused methods
- optimizing imports
- a few attributes could be final

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -import com.apple.foundationdb.LocalityUtil;
removing ununsed imports

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -        try {
redundant code as nothing was inside try catch.  also no 82-83 do not call foundation db.

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -            log.error("getSliceAsync db=%s, tx=%s with exception", name, txh, e);
migrating to slf4j parameterized logging

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -    public List<StaticBuffer> getBoundaryKeys() {
unused method

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBRangeQuery.java
> +    private final KVQuery originalQuery;
both these attributes could be final

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +    private final List<Insert> inserts = Collections.synchronizedList(new ArrayList<>());
all these attributes can be final

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        if (t instanceof FDBException) {
`t!=null` was redundant as `t instanceof FDBException` checks for null case as well

2021-06-24 16:38 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        private final byte[] key;
both the attributes could be final

2021-06-28 06:20 UTC, rngcntr requested changes
Thank you very much for cleaning up @nischalkumar, I appreciate that!
I have one remark, otherwise this PR looks good to me.

2021-06-28 06:20 UTC, rngcntr commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -    public List<StaticBuffer> getBoundaryKeys() {
This method was introduced by @ruweih and they stated the reason for its existence [here](https://github.com/JanusGraph/janusgraph-foundationdb/pull/48#discussion_r498917927). Instead of removing it, you could add a comment that says why it's there.

2021-06-28 16:49 UTC, nischalkumar commented on src/main/java/org/janusgraph/diskstorage/foundationdb/FoundationDBKeyValueStore.java
> -    public List<StaticBuffer> getBoundaryKeys() {
Resolved. Please let me know if i need to. update the comment.

2021-06-29 05:56 UTC, rngcntr approved these changes
That looks good, thanks!
Would you please squash your commits into a single one?

2021-06-29 08:31 UTC, rngcntr commented
Blocked on #61

2021-06-29 09:57 UTC, nischalkumar commented
> That looks good, thanks!
> Would you please squash your commits into a single one and resolve merge conflicts?
> 
> Edit: I just found out about the problems with our testing environment. I will try to go ahead and fix it so that CI will execute correctly.

I have squashed all commits into one. Conflicts are also resolved.

2021-06-29 11:55 UTC, rngcntr commented
@nischalkumar Very nice, thanks a lot for your contribution!

2021-06-29 11:55 UTC, merged